export type ImageCategory =
  | "company"
  | "hero"
  | "logos"
  | "machines"
  | "manufacturing"
  | "products"
  | "projects"
  | "quality"
  | "gallery";

export type ImageAsset = {
  src: string;
  alt: string;
  title: string;
  caption: string;
  category: ImageCategory;
  width: number;
  height: number;
  priority?: boolean;
  comingSoon?: boolean;
  recommendedPhoto?: string;
};

const asset = (image: ImageAsset) => image;

export const Images = {
  assets: {
    factoryBuildingExterior: asset({
      src: "/images/company/factory-building-exterior.webp",
      alt: "Pako Engineers factory building exterior in Sangli",
      title: "Factory Building Exterior",
      caption: "Exterior view of the Pako Engineers manufacturing facility.",
      category: "company",
      width: 1080,
      height: 684,
    }),
    factoryBuildingExteriorThumb: asset({
      src: "/images/company/factory-building-exterior.webp",
      alt: "Pako Engineers factory exterior thumbnail",
      title: "Factory Exterior Thumbnail",
      caption: "Compact exterior view for cards and previews.",
      category: "company",
      width: 1080,
      height: 684,
    }),
    factoryEntranceSignageThumb: asset({
      src: "/images/company/factory-entrance-signage.webp",
      alt: "Pako Engineers factory entrance signage",
      title: "Factory Entrance Signage",
      caption: "Factory entrance and signage at the manufacturing works.",
      category: "company",
      width: 360,
      height: 360,
    }),
    pakoEngineersBuildingSignageThumb: asset({
      src: "/images/company/pako-engineers-building-signage.webp",
      alt: "Pako Engineers building signage",
      title: "Building Signage",
      caption: "Pako Engineers signage on the facility building.",
      category: "company",
      width: 250,
      height: 250,
    }),
    ceoSudarshan: asset({
      src: "/images/company/leadership/ceo-sudarshan-khot.webp",
      alt: "Mr. Sudarshan Khot, Chief Executive Officer of Pako Engineers",
      title: "Mr. Sudarshan Khot",
      caption: "Chief Executive Officer",
      category: "company",
      width: 900,
      height: 1350,
    }),
    mdSuhas: asset({
      src: "/images/company/leadership/md-suhas-khot.webp",
      alt: "Mr. Suhas Khot, Managing Director of Pako Engineers",
      title: "Mr. Suhas Khot",
      caption: "Managing Director",
      category: "company",
      width: 900,
      height: 1350,
    }),
    cncTurningHero: asset({
      src: "/images/hero/homepage-hero.webp",
      alt: "Pako Engineers machine shop with heavy duty lathe operations",
      title: "Homepage Hero",
      caption: "Authentic view of heavy-duty machining operations at Pako Engineers.",
      category: "hero",
      width: 1537,
      height: 1023,
      priority: true,
    }),
    logo: asset({
      src: "/images/logos/pako-engineers-logo.png",
      alt: "Pako Engineers logo",
      title: "Pako Engineers Logo",
      caption: "Official Pako Engineers brand mark.",
      category: "logos",
      width: 1536,
      height: 1024,
      priority: true,
    }),
    cncOperatorMachineControlThumb: asset({
      src: "/images/machines/cnc-lathe-operator.webp",
      alt: "Machine operator working at CNC controls",
      title: "CNC Operator Machine Control",
      caption: "Operator setting up precision machining equipment.",
      category: "machines",
      width: 1200,
      height: 799,
    }),
    cylindricalGrindingMachine: asset({
      src: "/images/machines/cylindrical-grinding-machine.webp",
      alt: "Cylindrical grinding machine inside Pako Engineers facility",
      title: "Cylindrical Grinding Machine",
      caption: "Grinding capability for critical bearing and seal areas.",
      category: "machines",
      width: 1600,
      height: 1067,
    }),
    heavyDutyEngineLathe: asset({
      src: "/images/machines/heavy-duty-engine-lathe.webp",
      alt: "Heavy duty engine lathe on the factory floor",
      title: "Heavy Duty Engine Lathe",
      caption: "Large conventional turning capacity for heavy components.",
      category: "machines",
      width: 1537,
      height: 1023,
    }),
    heavyDutyLatheBed: asset({
      src: "/images/machines/heavy-duty-lathe-bed.webp",
      alt: "Long heavy duty lathe bed for machining large components",
      title: "Heavy Duty Lathe Bed",
      caption: "Long-bed turning setup for large shaft machining.",
      category: "machines",
      width: 1600,
      height: 1067,
    }),
    legacyLatheInspection: asset({
      src: "/images/machines/lathe-setup-inspection.webp",
      alt: "Operator inspecting a lathe setup",
      title: "Lathe Setup Inspection",
      caption: "Manual inspection and setup verification at the lathe.",
      category: "machines",
      width: 1400,
      height: 932,
    }),
    legacyLatheInspectionThumb: asset({
      src: "/images/machines/lathe-setup-inspection.webp",
      alt: "Lathe inspection thumbnail",
      title: "Lathe Inspection Thumbnail",
      caption: "Compact lathe inspection image for preview cards.",
      category: "machines",
      width: 1400,
      height: 932,
    }),
    longBedTurningLathe: asset({
      src: "/images/machines/long-bed-turning-lathe.webp",
      alt: "Long bed turning lathe in the Pako Engineers machine shop",
      title: "Long Bed Turning Lathe",
      caption: "Long-bed lathe used for precision shaft machining.",
      category: "machines",
      width: 1537,
      height: 1023,
    }),
    longBedTurningLatheThumb: asset({
      src: "/images/machines/long-bed-turning-lathe.webp",
      alt: "Long bed turning lathe thumbnail",
      title: "Long Bed Turning Lathe Thumbnail",
      caption: "Compact long-bed lathe image for gallery use.",
      category: "machines",
      width: 1537,
      height: 1023,
    }),
    longShaftMachiningLathe: asset({
      src: "/images/machines/long-shaft-machining-lathe.webp",
      alt: "Long shaft machining operation on a lathe",
      title: "Long Shaft Machining Lathe",
      caption: "Long shaft turning setup for precision component production.",
      category: "machines",
      width: 1537,
      height: 1023,
    }),
    machineOperatorLatheThumb: asset({
      src: "/images/machines/machine-operator-lathe.webp",
      alt: "Operator working beside a lathe",
      title: "Machine Operator Lathe",
      caption: "Operator and turning machine on the production floor.",
      category: "machines",
      width: 1400,
      height: 933,
    }),
    shaftMachiningLathe: asset({
      src: "/images/machines/shaft-machining-lathe.webp",
      alt: "Shaft machining on a heavy duty lathe",
      title: "Shaft Machining Lathe",
      caption: "Heavy-duty lathe machining for shafts and rotating components.",
      category: "machines",
      width: 1537,
      height: 1023,
    }),
    surfaceGrindingMachine: asset({
      src: "/images/machines/surface-grinding-machine.webp",
      alt: "Surface grinding machine in the manufacturing facility",
      title: "Surface Grinding Machine",
      caption: "Surface grinding equipment for precision finishing.",
      category: "machines",
      width: 1600,
      height: 1067,
    }),
    modernFactoryFloorOverview: asset({
      src: "/images/manufacturing/factory-floor-overview.webp",
      alt: "Pako Engineers factory floor overview",
      title: "Modern Factory Floor Overview",
      caption: "Wide overview of manufacturing capacity and shop-floor scale.",
      category: "manufacturing",
      width: 1537,
      height: 1023,
      priority: true,
    }),
    machinedCircularFlange: asset({
      src: "/images/products/machined-circular-flange.webp",
      alt: "Machined circular flange component",
      title: "Machined Circular Flange",
      caption: "Finished circular machined component with drilled bolt pattern.",
      category: "products",
      width: 1200,
      height: 900,
    }),
    machinedFlangeComponent: asset({
      src: "/images/products/machined-flange-component.webp",
      alt: "Finished machined flange component",
      title: "Machined Flange Component",
      caption: "Precision-machined flange component ready for inspection.",
      category: "products",
      width: 1200,
      height: 900,
    }),
    machinedSleeveComponents: asset({
      src: "/images/products/machined-sleeve-components.webp",
      alt: "Finished machined sleeve components",
      title: "Machined Sleeve Components",
      caption: "Finished sleeves and bush components machined to drawing.",
      category: "products",
      width: 1200,
      height: 900,
    }),
    precisionPumpShaftsLineup: asset({
      src: "/images/products/precision-pump-shafts-lineup.webp",
      alt: "Lineup of precision pump shafts and sleeves",
      title: "Precision Pump Shafts Lineup",
      caption: "Finished pump shafts and sleeves arranged after machining.",
      category: "products",
      width: 1200,
      height: 1800,
    }),
    pumpShaftsAndSleeves: asset({
      src: "/images/products/pump-shaft-components.webp",
      alt: "Pump shafts and sleeves manufactured by Pako Engineers",
      title: "Pump Shafts and Sleeves",
      caption: "Finished precision shafts, sleeves and machined pump components.",
      category: "products",
      width: 1023,
      height: 1537,
      priority: true,
    }),
    largePumpRotorAssembly: asset({
      src: "/images/projects/large-pump-rotor-assembly.webp",
      alt: "Large pump rotor assembly on the shop floor",
      title: "Large Pump Rotor Assembly",
      caption: "Large pump assembly work supported by overhead handling.",
      category: "projects",
      width: 1400,
      height: 1050,
      priority: true,
    }),
    largePumpRotorAssemblyThumb: asset({
      src: "/images/projects/large-pump-rotor-assembly.webp",
      alt: "Large pump rotor assembly thumbnail",
      title: "Large Pump Rotor Assembly Thumbnail",
      caption: "Compact assembly image for cards and preview galleries.",
      category: "projects",
      width: 1400,
      height: 1050,
    }),
    verticalPumpAssembly: asset({
      src: "/images/projects/vertical-pump-assembly.webp",
      alt: "Vertical pump assembly work in progress",
      title: "Vertical Pump Assembly",
      caption: "Vertical pump assembly and rotating equipment work.",
      category: "projects",
      width: 676,
      height: 450,
    }),
    verticalPumpAssemblyThumb: asset({
      src: "/images/projects/vertical-pump-assembly.webp",
      alt: "Vertical pump assembly thumbnail",
      title: "Vertical Pump Assembly Thumbnail",
      caption: "Compact vertical pump assembly image for cards.",
      category: "projects",
      width: 676,
      height: 450,
    }),
    precisionQualityInspection: asset({
      src: "/images/machines/lathe-setup-inspection.webp",
      alt: "Pako Engineers operator inspecting a lathe setup",
      title: "Machine Setup Inspection",
      caption: "Operator inspection and setup verification during machining.",
      category: "quality",
      width: 1400,
      height: 932,
      priority: true,
    }),
    gearComponents: asset({
      src: "/images/products/gear-components.webp",
      alt: "Machined gear components manufactured by Pako Engineers",
      title: "Gear Components",
      caption: "Finished gear components for industrial rotating equipment.",
      category: "products",
      width: 756,
      height: 1008,
    }),
    retainerBearingComponent: asset({
      src: "/images/products/retainer-bearing-component.webp",
      alt: "Machined retainer bearing component manufactured by Pako Engineers",
      title: "Retainer Bearing Component",
      caption: "Machined retainer and bearing component for pump applications.",
      category: "products",
      width: 864,
      height: 1152,
    }),
    rawMaterialStaging: asset({
      src: "/images/manufacturing/raw-material-staging.webp",
      alt: "Raw material staging area inside Pako Engineers factory",
      title: "Raw Material Staging",
      caption: "Raw material and bar stock staged for machining.",
      category: "manufacturing",
      width: 1537,
      height: 1023,
    }),
    longShaftMachiningLine: asset({
      src: "/images/machines/long-shaft-machining-lathe.webp",
      alt: "Long shaft machining line at Pako Engineers",
      title: "Long Shaft Machining Line",
      caption: "Long shaft machining setup in the production area.",
      category: "manufacturing",
      width: 1537,
      height: 1023,
    }),
    finishedShaftShopFloor: asset({
      src: "/images/products/pump-shaft-components.webp",
      alt: "Finished pump shaft on the Pako Engineers shop floor",
      title: "Finished Shaft Shop Floor",
      caption: "Finished pump shaft prepared after machining.",
      category: "manufacturing",
      width: 1023,
      height: 1537,
    }),
    edmMachine: asset({
      src: "/images/machines/edm-machine.webp",
      alt: "EDM machine inside Pako Engineers manufacturing facility",
      title: "EDM Machine",
      caption: "EDM capability for precision machining requirements.",
      category: "machines",
      width: 1400,
      height: 932,
    }),
    galleryLatheOperator: asset({
      src: "/images/machines/machine-operator-lathe.webp",
      alt: "Lathe operator at Pako Engineers",
      title: "Lathe Operator",
      caption: "Operator working at a lathe in the machine shop.",
      category: "gallery",
      width: 1400,
      height: 933,
    }),
    galleryMachineShopOverview: asset({
      src: "/images/machines/heavy-duty-engine-lathe.webp",
      alt: "Machine shop overview at Pako Engineers",
      title: "Machine Shop Overview",
      caption: "Overview of heavy-duty turning equipment in the factory.",
      category: "gallery",
      width: 1537,
      height: 1023,
    }),
    galleryFinishedPumpShaft: asset({
      src: "/images/products/pump-shaft-components.webp",
      alt: "Finished pump shaft manufactured by Pako Engineers",
      title: "Finished Pump Shaft",
      caption: "Finished pump shaft on the shop floor.",
      category: "gallery",
      width: 1023,
      height: 1537,
    }),
    galleryGrindingMachineOperator: asset({
      src: "/images/machines/grinding-machine-operator.webp",
      alt: "Grinding machine operator at Pako Engineers",
      title: "Grinding Machine Operator",
      caption: "Operator working beside a grinding machine.",
      category: "gallery",
      width: 1200,
      height: 799,
    }),
    galleryLargeBoringMachine: asset({
      src: "/images/machines/large-boring-machine.webp",
      alt: "Large boring machine at Pako Engineers",
      title: "Large Boring Machine",
      caption: "Large boring machine used for heavy component machining.",
      category: "gallery",
      width: 1200,
      height: 799,
    }),
    galleryLongShaftMachining: asset({
      src: "/images/machines/long-shaft-machining-lathe.webp",
      alt: "Long shaft machining at Pako Engineers",
      title: "Long Shaft Machining",
      caption: "Long shaft machining work in progress.",
      category: "gallery",
      width: 1537,
      height: 1023,
    }),
    galleryRawMaterialStaging: asset({
      src: "/images/manufacturing/raw-material-staging.webp",
      alt: "Raw material staged for machining at Pako Engineers",
      title: "Raw Material Staging",
      caption: "Raw materials arranged near heavy turning machines.",
      category: "gallery",
      width: 1537,
      height: 1023,
    }),
    galleryCncMachineOperator: asset({
      src: "/images/machines/cnc-lathe-operator.webp",
      alt: "CNC machine operator at Pako Engineers",
      title: "CNC Machine Operator",
      caption: "Operator beside a CNC machine inside the facility.",
      category: "gallery",
      width: 1200,
      height: 799,
    }),
    galleryEdmMachine: asset({
      src: "/images/machines/edm-machine.webp",
      alt: "EDM machine in the Pako Engineers facility",
      title: "EDM Machine",
      caption: "EDM machine used for precision manufacturing support.",
      category: "gallery",
      width: 1400,
      height: 932,
    }),
    galleryVmcMachineOperator: asset({
      src: "/images/machines/vmc-machine-operator.webp",
      alt: "VMC machine operator at Pako Engineers",
      title: "VMC Machine Operator",
      caption: "Operator working with a vertical machining center.",
      category: "gallery",
      width: 1200,
      height: 799,
    }),
  },
} as const;

export const ImageGroups = {
  hero: {
    homepage: Images.assets.cncTurningHero,
    company: Images.assets.modernFactoryFloorOverview,
    products: Images.assets.pumpShaftsAndSleeves,
    projects: Images.assets.largePumpRotorAssembly,
    services: Images.assets.shaftMachiningLathe,
    quality: Images.assets.precisionQualityInspection,
    manufacturing: Images.assets.cncTurningHero,
    contact: Images.assets.factoryBuildingExterior,
    rfq: Images.assets.precisionQualityInspection,
  },
  openGraph: {
    homepage: Images.assets.cncTurningHero,
    company: Images.assets.modernFactoryFloorOverview,
    products: Images.assets.pumpShaftsAndSleeves,
    projects: Images.assets.largePumpRotorAssembly,
    services: Images.assets.shaftMachiningLathe,
    contact: Images.assets.factoryBuildingExterior,
    rfq: Images.assets.precisionQualityInspection,
  },
  products: {
    shaft: {
      primary: Images.assets.pumpShaftsAndSleeves,
      secondary: Images.assets.precisionPumpShaftsLineup,
      hero: Images.assets.pumpShaftsAndSleeves,
      gallery: [
        Images.assets.pumpShaftsAndSleeves,
        Images.assets.cncTurningHero,
        Images.assets.largePumpRotorAssemblyThumb,
        Images.assets.precisionQualityInspection,
      ],
    },
    sleeve: {
      primary: Images.assets.machinedSleeveComponents,
      secondary: Images.assets.precisionQualityInspection,
      hero: Images.assets.machinedSleeveComponents,
      gallery: [Images.assets.machinedSleeveComponents, Images.assets.precisionQualityInspection],
    },
    impeller: {
      primary: Images.assets.machinedFlangeComponent,
      hero: Images.assets.machinedFlangeComponent,
      gallery: [Images.assets.machinedFlangeComponent],
      comingSoon: true,
      recommendedPhoto: "Dedicated machined and balanced impeller product photo",
    },
    coupling: {
      primary: Images.assets.machinedCircularFlange,
      hero: Images.assets.machinedCircularFlange,
      gallery: [Images.assets.machinedCircularFlange],
      comingSoon: true,
      recommendedPhoto: "Dedicated coupling product photo",
    },
    pumpParts: {
      primary: Images.assets.longBedTurningLathe,
      secondary: Images.assets.cncTurningHero,
      hero: Images.assets.longBedTurningLathe,
      gallery: [Images.assets.longBedTurningLathe, Images.assets.cncTurningHero],
      comingSoon: true,
      recommendedPhoto: "Assorted custom pump parts arranged on a clean inspection surface",
    },
    lockNut: {
      primary: Images.assets.machinedCircularFlange,
      hero: Images.assets.machinedCircularFlange,
      gallery: [Images.assets.machinedCircularFlange],
      comingSoon: true,
      recommendedPhoto: "Dedicated precision lock nut close-up",
    },
    retainerRing: {
      primary: Images.assets.retainerBearingComponent,
      hero: Images.assets.retainerBearingComponent,
      gallery: [Images.assets.retainerBearingComponent, Images.assets.machinedSleeveComponents],
      comingSoon: true,
      recommendedPhoto: "Additional retainer ring and bearing assembly photos",
    },
    gears: {
      primary: Images.assets.gearComponents,
      hero: Images.assets.gearComponents,
      gallery: [Images.assets.gearComponents, Images.assets.shaftMachiningLathe],
      comingSoon: true,
      recommendedPhoto: "Additional custom gear and gear shaft product photos",
    },
  },
  services: {
    cncTurning: {
      hero: Images.assets.cncTurningHero,
      machinery: Images.assets.shaftMachiningLathe,
      process: Images.assets.longBedTurningLathe,
      finishedProduct: Images.assets.pumpShaftsAndSleeves,
    },
    grinding: {
      hero: Images.assets.cylindricalGrindingMachine,
      machinery: Images.assets.surfaceGrindingMachine,
      process: Images.assets.legacyLatheInspection,
      finishedProduct: Images.assets.machinedSleeveComponents,
    },
    milling: {
      hero: Images.assets.machineOperatorLatheThumb,
      machinery: Images.assets.cncOperatorMachineControlThumb,
      process: Images.assets.longShaftMachiningLathe,
      finishedProduct: Images.assets.machinedCircularFlange,
      comingSoon: true,
      recommendedPhoto: "Dedicated VMC milling or key-way machining photo",
    },
    assembly: {
      hero: Images.assets.largePumpRotorAssembly,
      machinery: Images.assets.verticalPumpAssembly,
      process: Images.assets.verticalPumpAssemblyThumb,
      finishedProduct: Images.assets.largePumpRotorAssemblyThumb,
    },
    inspection: {
      hero: Images.assets.precisionQualityInspection,
      machinery: Images.assets.legacyLatheInspectionThumb,
      process: Images.assets.precisionQualityInspection,
      finishedProduct: Images.assets.machinedFlangeComponent,
      comingSoon: true,
      recommendedPhoto: "Dedicated CMM inspection equipment photo",
    },
    engineering: {
      hero: Images.assets.modernFactoryFloorOverview,
      machinery: Images.assets.heavyDutyEngineLathe,
      process: Images.assets.heavyDutyLatheBed,
      finishedProduct: Images.assets.precisionPumpShaftsLineup,
    },
  },
  placeholders: {
    managementTeamPortraits: {
      comingSoon: true,
      recommendedPhoto: "Management team portraits",
    },
    isoCertificates: {
      comingSoon: true,
      recommendedPhoto: "High-resolution ISO certificate scans",
    },
    cmmInspection: {
      comingSoon: true,
      recommendedPhoto: "Dedicated CMM inspection equipment photo",
    },
    vmcMachining: {
      comingSoon: true,
      recommendedPhoto: "VMC machining or key-way machining photo",
    },
    edmMachining: {
      comingSoon: true,
      recommendedPhoto: "Wire-cut EDM machining photo",
    },
    exportPackaging: {
      comingSoon: true,
      recommendedPhoto: "Export packaging and wooden crating photo",
    },
    warehouse: {
      comingSoon: true,
      recommendedPhoto: "Warehouse and raw material storage photo",
    },
    rawMaterials: {
      comingSoon: true,
      recommendedPhoto: "Raw material bars, forgings, and incoming stock photo",
    },
  },
} as const;

export const publicImageUrl = (image: ImageAsset) => image.src;
export const absoluteImageUrl = (image: ImageAsset) => `https://pakoshaft.com${image.src}`;
